
install(FILES src/ZNamespace.h src/ZNative.h
        DESTINATION ${ZNATIVE_INCLUDE_INSTALL_DIR})
install(DIRECTORY src/common
        DESTINATION ${ZNATIVE_INCLUDE_INSTALL_DIR}
        FILES_MATCHING PATTERN "*.h")
install(DIRECTORY ${PLATFORM_SRC_PATH}
        DESTINATION ${ZNATIVE_INCLUDE_INSTALL_DIR}
        FILES_MATCHING PATTERN "*.h")
# install third-party libs
install(FILES ${COMMON_LIBS_PATH}/tinyformat/tinyformat.h
        DESTINATION ${THIRDPARTY_INCLUDE_INSTALL_DIR})
install(DIRECTORY ${COMMON_LIBS_PATH}/json/nlohmann
        DESTINATION ${THIRDPARTY_INCLUDE_INSTALL_DIR})
install(DIRECTORY ${COMMON_LIBS_PATH}/eventpp-0.1.3/include/eventpp
        DESTINATION ${THIRDPARTY_INCLUDE_INSTALL_DIR})
install(DIRECTORY ${COMMON_LIBS_PATH}/libyuv-stable/include/libyuv
        DESTINATION ${THIRDPARTY_INCLUDE_INSTALL_DIR})
install(FILES ${COMMON_LIBS_PATH}/libyuv-stable/include/libyuv.h
        DESTINATION ${THIRDPARTY_INCLUDE_INSTALL_DIR})

if (${ZNATIVE_INSTALL_STATIC})
    install(TARGETS ${TARGET_STATIC} DESTINATION ${CMAKE_INSTALL_PREFIX}/libs/${TARGET_ARCH})
else ()
    install(TARGETS ${TARGET_SHARED} DESTINATION ${CMAKE_INSTALL_PREFIX}/libs/${TARGET_ARCH})
endif ()

install(FILES cmake/ZNativeConfig.cmake DESTINATION ${CMAKE_INSTALL_PREFIX})